### PR TITLE
Fix d3v7: transition, scale, toCircle/Stick

### PR DESCRIPTION
**Pull request by EliotRagueneau**
Fixing some issues that came with the update to d3 v7: 

- [x] Transition are now fixed by stoping the timer when finished  [See commit](https://github.com/MICommunity/ComplexViewer/commit/c1d591f705eb43cdc52f28c65e3f55b0a9b74645)
- [x] Scale switching is now fixed by using the data change instead of the chenge event in new API [See commit](https://github.com/MICommunity/ComplexViewer/commit/f311c48097de68d4f9759c6290ada41ebe9b7437)
- [x] Transform fixed by removing dependency to d3-transform and using "home-made" parser for transform instead [See commit](https://github.com/MICommunity/ComplexViewer/commit/49e28caa567f383a18c2d84a61ba7140caaabf94)

From my shallow testing, I couldn't find any other big issues stopping the upgrade to d3v7, please confirm that by testing the solutions proposed and if the new complex viewer is working as expected. Also I took the liberty to reformat slightly some lines of codes, feel free to discard those commits

### CODE REVIEW

**Review by colin-combe — COMMENTED** [review]
Hi Eliot - great! Thanks for this. You should be added as a contributor in package.json.

I think I can see one problem - the UniprotKB and Superfamily annotations aren't loading?

cheers,
Colin

**Comment by EliotRagueneau** [comment]
I have now fixed the fetching of data using d3-fetch, fixed the parsing of some super families which were having html encoded characters and increased the limit of color.

Please tell me if you see any other issues

**Comment by colin-combe** [comment]
yes, it seems to work. I'd be happy to merge that pull request.

> increased the limit of color
I have my doubts about whether those 20 colours can really be easily distinguished. But if you want it like that then that's fine.

I can do the npm release after its been merged.

**Comment by EliotRagueneau** [comment]
Yes I agree those colors are not perfect, but actually I don't think they are any combinaisons of 20 colours without at least 2 very similar

**Comment by colin-combe** [comment]
yes, i agree, so why increase number of colours to 20 if 20 colours can't be distinguished?

I'm just being argumentative ;) have it like that if you wish

**Comment by EliotRagueneau** [comment]
Fair point, it's just that I was landing on issues with not having enough colors so everything became black, I just wanted to extend a bit the limit before UI breaks, but it's definetively arbitrary

**Comment by colin-combe** [comment]
ok, i thought it would cycle through the colours again when it ran out, not make everything black, that was the intended behaviour... doesn't really matter

**Comment by colin-combe** [comment]
updated it on npm 
https://www.npmjs.com/package/complexviewer

**Pull request merged**
