### PR TITLE
copies of same complex are same colour, ?-79 position, tooltip bug, complex stoich

### PR DESCRIPTION
**Pull request by colin-combe**
- fix tooltip bug (was displaying old tooltip if clicked on background)
- duplicated/cloned copies of same complex have same colour
- handle position like "?-79" (CPX-1924, psi binding region)
- expand complex stoich (CPX-1924)

CPX-7083 is broken (because of nested complexes requiring duplication)

### CODE REVIEW

**Comment by EliotRagueneau** [comment]
Should we try to fix CPX-7083 before publishing a new release?

**Comment by colin-combe** [comment]
it's up to you, but i'm thinking CPX-7083 is not so easy to fix. 
See my comment in https://github.com/MICommunity/ComplexViewer/issues/202

I don't think i understand why the code we have (mostly) works. I was thinking of putting it on the back burner for times when i was looking for a puzzle. 

let me know if you have any help or suggestions about it

**Comment by EliotRagueneau** [comment]
Okay sounds about right, I'll deploy version 2.2.2 then, and push it to complex portal and intact. Also, I wanted to tell you that UniProt just embedded your viewer within their website: https://www.uniprot.org/uniprotkb/Q15554/entry#interaction, so this update will probably be pushed on their side as well

**Comment by EliotRagueneau** [comment]
Hi @colin-combe , I realised that you deployed the viewer using your credentials, therefore I cannot publish v2.2.2 to NPM. Do you think you could do it?
Once done, I will be able to use it across our ressources.
Also, before realising that, I did try to build the package and faced a problem with node OPENSSL issue, and have updated webpack to fix the issue. Everything seems to be working still, but worth checking I guess.

**Comment by colin-combe** [comment]
Hi @EliotRagueneau,
it built fine for me before, and it still builds fine for me after your webpack update.

I have updated it on npm - https://www.npmjs.com/package/complexviewer

Cheers,
C

**Pull request merged**
